service: govuk-docs
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    MODE: serverless
    NODE_ENV: production
package:
  include:
    - dist/**
  exclude:
    - node_modules/**
    - src/**
    - ./**
functions:
  server:
    handler: dist/server/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
