packages:
  - apps/**
  - components/**
  - lib/**
dedupePeerDependents: true          # Default
resolutionMode: highest             # Default
resolvePeersFromWorkspaceRoot: true # Default
autoInstallPeers: false             # Needed to avoid build errors
onlyBuiltDependencies:
  - bun                             # Required in v10
  - cypress                         # Required in v10
