packages:
  - apps/**
  - components/**
  - components-internal/**
  - lib/**
  - lib-govuk/**
dedupePeerDependents: true          # Default
resolutionMode: highest             # Default
resolvePeersFromWorkspaceRoot: true # Default
autoInstallPeers: false             # Needed to avoid build errors
onlyBuiltDependencies:
  - cypress                         # Required in v10
