name: Publish
description: Publish all public packages
inputs:
  npm-token:
    description: NPM token to publish with
    required: true
  version:
    description: Version to publish
    required: true
runs:
  using: composite
  steps:

    - name: Publish
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
        VERSION: ${{ inputs.version }}
      run: |
        git config --global user.name "publish+github-actions[bot]"
        git config --global user.email "publish+github-actions[bot]@users.noreply.github.com"
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm version "${VERSION}"
        npm run all:publish
        git push
        git push --tags
