name: Build application
description: Build and test a NotGovUK application
inputs:
  app:
    required: true
    type: string
  cypress-project-id:
    required: false
  cypress-record-key:
    required: false
runs:
  using: composite
  steps:

    - name: Build application
      env:
        NODE_OPTIONS: --max_old_space_size=6144
      shell: bash
      working-directory: './apps/${{ inputs.app }}/'
      run: 'npm run build'

    - name: Setup Firefox
      uses: browser-actions/setup-firefox@latest
      if: inputs.browser == 'firefox'

    - name: Setup Chromium
      uses: browser-actions/setup-chromium@latest
      if: inputs.browser == 'chromium'

    - name: Run functional tests
      uses: './.github/actions/test-app'
      with:
        app: ${{ inputs.app }}
        cypress-project-id: ${{ inputs.cypress-project-id }}
        cypress-record-key: ${{ inputs.cypress-record-key }}

    - uses: actions/upload-artifact@master
      if: failure()
      with:
        name: screenshots
        path: 'apps/${{ inputs.app }}/.cypress/screenshots'
