name: Scan code-base
description: Scans the code-base for credentials and security vulnerabilities
inputs:
  token:
    description: GitHub token
    required: true
  baseline-branch:
    description: Name of branch to store baseline on
    required: false
    default: master
runs:
  using: composite
  steps:

    - name: Cache vdb
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/vdb
        key: vdb-os_${{ runner.os }}

    - name: Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        CREDSCAN_DEPTH: 20
        DISABLE_TELEMETRY: 'true'
        ENABLE_OSS_RISK: 'true'
        FETCH_LICENSE: 'true'
        VDB_HOME: ${{ github.workspace }}/vdb
        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        type: credscan,nodejs,json,yaml,serverless,dockerfile,kubernetes,depscan,bom
        output: reports

    - name: Upload scan reports
      uses: actions/upload-artifact@master
      with:
        name: slscan-reports
        path: reports

    - name: Update scan baseline
      shell: bash
      if: ${{ github.ref == 'refs/heads/${{ inputs.baseline-branch }}' }}
      run: |
        cp reports/.sastscan.baseline .
        git add -f .sastscan.baseline
        git config --global user.name "scan+github-actions[bot]"
        git config --global user.email "scan+github-actions[bot]@users.noreply.github.com"
        git commit -m "Update slscan baseline"
        git push
