import type { Metadata, Viewport } from "next";
import React from "react";
import { NotGovUKPage } from '@not-govuk/simple-components';
import { AddBodyClass } from '../components/AddBodyClass';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export const viewport: Viewport = {
  themeColor: '#0b0c0c'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AddBodyClass />
        <NotGovUKPage
          breadcrumbs={[
            {
              href: "/",
              text: "Home"
            },
            {
              href: "/one",
              text: "One"
            },
            {
              href: "/one/two",
              text: "Two"
            }
          ]}
          feedbackHref="/feedback"
          navigation={[
            {
              href: "/one",
              text: "One"
            },
            {
              href: "/one/two",
              text: "Two"
            },
            {
              href: "/three",
              text: "Three"
            },
            {
              href: "/four",
              text: "Four"
            }
          ]}
          organisationHref="/"
          organisationText="!GOV.UK"
          phase="alpha"
          serviceName="Next.js App"
          serviceHref="/"
          title="NotGovUK"
        >
          {children}
        </NotGovUKPage>
      </body>
    </html>
  );
}
