name: Main
on:
  - pull_request
  - push
jobs:
  common:
    name: Dependencies, Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}

      - name: Run unit tests
        run: npm test

  libs:
    name: Build libraries
    needs:
      - common
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}

      - name: Build libraries
        run: npm run libs:build

  chromatic:
    name: Chromatic
    needs:
      - libs
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        node: [ '12' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}

      - name: Push Storybook to Chromatic
        env:
          NODE_OPTIONS: --max_old_space_size=6144
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'build:storybook'
          autoAcceptChanges: master
          exitZeroOnChanges: true
          exitOnceUploaded: true

  build-app:
    name: Build application
    needs:
      - common
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ 'govuk-docs', 'govuk-template' ]
        node: [ '12' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}

      - name: Build
        uses: ./.github/actions/build-app
        with:
          app: ${{ matrix.app }}
          cypress-project-id: ${{ secrets.CYPRESS_PROJECT_ID }}
          cypress-record-key: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Save build directory
        uses: actions/upload-artifact@v2
        with:
          name: 'build-${{ matrix.app }}'
          path: 'apps/${{ matrix.app }}/dist'
          if-no-files-found: error
          retention-days: 2

  deploy-docs-to-netlify:
    name: Deploy docs to Netlify
    needs:
      - build-app
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        node: [ '12' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}

      - name: Download build directory
        uses: actions/download-artifact@v2
        with:
          name: 'build-govuk-docs'
          path: 'apps/govuk-docs/dist'

      - name: Deploy
        uses: ./.github/actions/deploy-to-netlify
        with:
          app: govuk-docs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
