name: Main
on:
  - pull_request
  - push
jobs:
  common:
    name: Dependencies, Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Cache Cypress.io
        uses: actions/cache@v2
        env:
          cache-hash: ${{ hashFiles('pnpm-lock.yaml') }}
        with:
          path: '~/.cache/Cypress'
          key: cypress-os_${{ runner.os }}-lock_${{ env.cache-hash }}

      - name: Pull dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.13.0
          run_install: true

      - name: Run unit tests
        run: npm test

  libs:
    name: Build libraries
    needs:
      - common
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Cache Cypress.io
        uses: actions/cache@v2
        env:
          cache-hash: ${{ hashFiles('pnpm-lock.yaml') }}
        with:
          path: '~/.cache/Cypress'
          key: cypress-os_${{ runner.os }}-lock_${{ env.cache-hash }}

      - name: Pull dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.13.0
          run_install: true

      - name: Build libraries
        run: npm run libs:build

  chromatic:
    name: Chromatic
    needs:
      - libs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Cache Cypress.io
        uses: actions/cache@v2
        env:
          cache-hash: ${{ hashFiles('pnpm-lock.yaml') }}
        with:
          path: '~/.cache/Cypress'
          key: cypress-os_${{ runner.os }}-lock_${{ env.cache-hash }}

      - name: Pull dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.13.0
          run_install: true

      - name: Push Storybook to Chromatic
        env:
          NODE_OPTIONS: --max_old_space_size=6144
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'build:storybook'
          autoAcceptChanges: master
          exitZeroOnChanges: true
          exitOnceUploaded: true

  build-app:
    name: Build application
    needs:
      - common
    strategy:
      matrix:
        app: [ 'govuk-docs', 'govuk-template' ]
    uses: ./.github/workflows/build-app.yml
    with:
      app: ${{ matrix.app }}
    secrets:
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  deploy-docs-to-netlify:
    name: Deploy docs to Netlify
    needs:
      - build-app
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/deploy-to-netlify.yml
    with:
      app: govuk-docs
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
