name: Test
on:
  - push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        env:
          cache-hash: ${{ hashFiles('pnpm-lock.yaml') }}
        with:
          path: ~/.pnpm-store
          key: pnpm-os_${{ runner.os }}-node_${{ matrix.node }}-lock_${{ env.cache-hash }}
          restore-keys: |
            pnpm-os_${{ runner.os }}-node_${{ matrix.node }}-
            pnpm-os_${{ runner.os }}-
            pnpm-

      - name: Pull dependencies
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.4.0
          run_install: true

      - name: Run unit tests
        run: npm test

      - name: Build Storybook
        run: |
          cd .tools/storybook
          npm run build-storybook

      - name: Push Storybook to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: .tools/storybook/storybook-static
          autoAcceptChanges: master
          exitZeroOnChanges: true

      - name: Build applications (WRITEME!)
        run: echo 'UNIMPLEMENTED'

      - name: Test applications (WRITEME!)
        run: echo 'UNIMPLEMENTED'
